from enum import Enum

class EventType(Enum):
    DEVICE_ONLINE = "DEVICE_ONLINE"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"

    GPS_RECEIVED = "GPS_RECEIVED"

    HEARTBEAT = "HEARTBEAT"

    IGNITION_ON = "IGNITION_ON"
    IGNITION_OFF = "IGNITION_OFF"

    MOVEMENT_STARTED = "MOVEMENT_STARTED"
    MOVEMENT_STOPPED = "MOVEMENT_STOPPED"

    LOW_BATTERY = "LOW_BATTERY"

    POWER_CONNECTED = "POWER_CONNECTED"
    POWER_DISCONNECTED = "POWER_DISCONNECTED"

    GPS_FIX_LOST = "GPS_FIX_LOST"
    GPS_FIX_RESTORED = "GPS_FIX_RESTORED"

    OVERSPEED = "OVERSPEED"

    GEOFENCE_ENTER = "GEOFENCE_ENTER"
    GEOFENCE_EXIT = "GEOFENCE_EXIT"

    SOS = "SOS"

    ENGINE_CUT = "ENGINE_CUT"
    ENGINE_RESTORED = "ENGINE_RESTORED"

    COMMAND_SUCCESS = "COMMAND_SUCCESS"
    COMMAND_FAILED = "COMMAND_FAILED"

    DEVICE_INFORMATION = "DEVICE_INFORMATION"
    DEVICE_CONFIGURATION = "DEVICE_CONFIGURATION"